/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Juego;

import cartas.Nivel;
import javax.swing.JOptionPane;

/**
 *
 * @author UTN
 */
public class FrmJuegoMemoria extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmJuegoMemoria.class.getName());

    /**
     * Creates new form FrmJuegoMemoria
     */
    public FrmJuegoMemoria() {
        initComponents();
        setExtendedState(FrmJuegoMemoria.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxNivel = new javax.swing.JComboBox<>();
        DPnivel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego de Memoria");
        addWindowStateListener(this::formWindowStateChanged);

        boxNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principiante", "Intermedio", "Avanzado" }));
        boxNivel.addActionListener(this::boxNivelActionPerformed);

        javax.swing.GroupLayout DPnivelLayout = new javax.swing.GroupLayout(DPnivel);
        DPnivel.setLayout(DPnivelLayout);
        DPnivelLayout.setHorizontalGroup(
            DPnivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DPnivelLayout.setVerticalGroup(
            DPnivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(boxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 460, Short.MAX_VALUE))
            .addComponent(DPnivel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DPnivel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNivelActionPerformed
        switch(boxNivel.getSelectedIndex()){
            case 0 -> {
                JOptionPane.showMessageDialog(this,"Selecciono Principiante"); 
                mostrar(new VentanaPrincipiante());
        }   
            case 1 -> {
                JOptionPane.showMessageDialog(this,"Selecciono Intermedio"); 
                mostrar(new VentanaIntermedio());
        }
            case 2 -> {
                JOptionPane.showMessageDialog(this,"Selecciono Avanzado");  
                mostrar(new VentanaAvanzado());
        }
        }
    }//GEN-LAST:event_boxNivelActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged
private void mostrar(javax.swing.JInternalFrame ventana) {
    DPnivel.removeAll();
    DPnivel.add(ventana);
    ventana.setSize(DPnivel.getSize());
    ventana.setVisible(true);
    DPnivel.repaint();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmJuegoMemoria().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DPnivel;
    private javax.swing.JComboBox<String> boxNivel;
    // End of variables declaration//GEN-END:variables
}
